name: PromptCC_env
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2024.9.24
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.9.20
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - 2to3==1.0
      - asttokens==2.1.0
      - async-generator==1.10
      - attrs==22.2.0
      - backcall==0.2.0
      - brotlipy==0.7.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==2.1.1
      - click==8.1.3
      - clip==1.0
      - cloudpickle==3.1.0
      - cog==0.0.3
      - colorama==0.4.6
      - contourpy==1.3.0
      - cryptography==43.0.3
      - cycler==0.12.1
      - cytoolz==0.11.0
      - dask==2024.8.0
      - decorator==5.1.1
      - exceptiongroup==1.1.0
      - executing==1.2.0
      - faiss-gpu==1.7.2
      - filelock==3.8.0
      - fonttools==4.25.0
      - fsspec==2024.10.0
      - ftfy==6.1.1
      - h11==0.14.0
      - h5py==3.12.1
      - huggingface-hub==0.9.1
      - idna==3.4
      - imagecodecs==2024.9.22
      - imageio==2.36.0
      - imgaug==0.4.0
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - intel-cmplr-lib-ur==2024.2.1
      - intel-openmp==2024.2.1
      - ipython==8.6.0
      - jedi==0.18.1
      - jieba==0.42.1
      - jinja2==3.1.4
      - joblib==1.2.0
      - kiwisolver==1.4.7
      - locket==1.0.0
      - loguru==0.7.2
      - markupsafe==3.0.2
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.6
      - mkl==2024.2.2
      - mkl-fft==1.3.8
      - mkl-random==1.2.4
      - mkl-service==2.4.0
      - mpmath==1.3.0
      - munkres==1.1.4
      - networkx==3.2.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - opencv-python==4.8.0.74
      - outcome==1.2.0
      - packaging==24.1
      - pandas==2.0.3
      - parso==0.8.3
      - partd==1.4.2
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==9.2.0
      - prompt-toolkit==3.0.31
      - ptflops==0.7
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pycparser==2.22
      - pygments==2.13.0
      - pynvml==11.4.1
      - pyopenssl==24.2.1
      - pyparsing==3.2.0
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - pytz==2023.3
      - pywavelets==1.6.0
      - pyyaml==6.0
      - regex==2022.9.13
      - requests==2.32.3
      - sacremoses==0.0.53
      - scikit-image==0.18.1
      - scipy==1.13.1
      - selenium==4.7.2
      - shapely==1.8.5.post1
      - six==1.16.0
      - sniffio==1.3.0
      - sortedcontainers==2.4.0
      - stack-data==0.6.0
      - sympy==1.13.1
      - tbb==2021.13.1
      - thop==0.1.1-2209072238
      - tifffile==2024.8.30
      - tokenizers==0.10.3
      - toolz==1.0.0
      - torch==2.5.0
      - torchaudio==2.5.0
      - torchinfo==1.8.0
      - torchstat==0.0.7
      - torchsummary==1.5.1
      - torchvision==0.20.0
      - tqdm==4.64.1
      - traitlets==5.5.0
      - transformers==4.10.3
      - trio==0.22.0
      - trio-websocket==0.9.2
      - triton==3.1.0
      - typing-extensions==4.12.2
      - tzdata==2023.3
      - urllib3==1.26.12
      - wcwidth==0.2.5
      - win-inet-pton==1.1.0
      - win32-setctime==1.1.0
      - wincertstore==0.2
      - wsproto==1.2.0
      - zipp==3.20.2
